# Generated by Django 5.1.2 on 2025-01-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender_en_user_gender_ru_user_gender_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender_uz',
        ),
    ]
