# Generated by Django 5.1.2 on 2024-12-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
