# Generated by Django 5.1.2 on 2024-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Terrible', 'Terrible'), ('Bad', 'Bad'), ('Normal', 'Normal'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default/course.png', upload_to='courses/'),
        ),
    ]
